project-1-team-infinite/force-app/main/default/objects/Mail__c/Mail__c.object-meta.xml
<CustomObject>
    <label>Mail</label>
    <nameField>
        <displayFormat>Mail-{0000}</displayFormat>
        <label>Mail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

project-1-team-infinite/force-app/main/default/objects/Mail__c/fields/Delivery_Status__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Status__c</fullName>
    <label>Delivery Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inventoried</fullName>
            </value>
            <value>
                <fullName>Missing</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

project-1-team-infinite/force-app/main/default/classes/TrackingCodeSearchController.cls
public class TrackingCodeSearchController {
    
    public List<Mail__c> mailList {get;set;}
    public String name {get;set;}
    public static string newQuery {get;set;} 
    public TrackingCodeSearchController() {

        mailList = new List<Mail__c>();
        
    }
    
    public PageReference searchMail() {
        mailList =[SELECT name, delivery_status__C 
	   			    FROM mail__C 
	   				WHERE name = :name];
        System.debug(mailList);
        
        return null;
    }
}