project-1-team-infinite/force-app/main/default/objects/Inhabitant__c/Inhabitant__c.object-meta.xml
<CustomObject>
    <label>Inhabitant</label>
    <nameField>
        <displayFormat>Inhabitant-{0000}</displayFormat>
        <label>Inhabitant Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inhabitants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

project-1-team-infinite/force-app/main/default/objects/Mail__c/Mail__c.object-meta.xml
<CustomObject>
    <label>Mail</label>
    <nameField>
        <displayFormat>Mail-{0000}</displayFormat>
        <label>Mail Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

project-1-team-infinite/force-app/main/default/objects/Mail__c/fields/Delivery_Status__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Status__c</fullName>
    <label>Delivery Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inventoried</fullName>
            </value>
            <value>
                <fullName>Missing</fullName>
            </value>
            <value>
                <fullName>Out for Delivery</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

project-1-team-infinite/force-app/main/default/objects/Mail__c/fields/Estimate_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Estimate_Delivery__c</fullName>
    <formula>CreatedDate + 7</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Estimate Delivery</label>
    <type>DateTime</type>
</CustomField>

project-1-team-infinite/force-app/main/default/objects/Mail__c/fields/Inhabitant__c.field-meta.xml
<CustomField>
    <fullName>Inhabitant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inhabitant</label>
    <referenceTo>Inhabitant__c</referenceTo>
    <relationshipLabel>Mail</relationshipLabel>
    <relationshipName>Mail</relationshipName>
    <type>Lookup</type>
</CustomField>

project-1-team-infinite/force-app/main/default/classes/PackagesInShippingController.cls
public class PackagesInShippingController {
    
    Map<String, String> session = AUTH.sessionmanagement.getcurrentsession();
    String UserId = session.get('UsersId');
    public List<Mail__C> mailList{get;set;}
    User u = [Select ContactID, Id from User WHERE Id =: UserId];
    
    
    public PackagesInShippingController(){
    	
    	List<Inhabitant__c> inhab;
       
        try{
        Contact c = [select Id from contact WHERE Id =: u.ContactId];
        
        inhab = new List<Inhabitant__c>();
        
        for(inhabitant__C i : [select id from inhabitant__c where Contact__c =: c.id]){
            inhab.add(i);
        }
        } catch(exception e){
            system.debug(e);
        }
        
                
        maillist = new list<mail__c>();
        
        try{
        for(inhabitant__C i : inhab){
            for(mail__c m : [SELECT name, Delivery_Status__C, Estimate_Delivery__c from Mail__C where (Delivery_Status__c != 'Delivered' AND Delivery_Status__c != 'Missing') AND inhabitant__c =: i.id]){
                maillist.add(m);
            }
        }
        
    } catch(exception f){
            system.debug(f);
        }
       
    }
    
}